language: python

python:
  - "2.7"

install:
  - python setup.py -q install
  - pip install coverage pytest-cov coveralls --use-mirrors

script: 
    python setup.py test

after_success:
    coveralls
